/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRepairsIndexRouteImport } from './routes/_authenticated/repairs.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedMachinesMachineIdRouteImport } from './routes/_authenticated/machines.$machineId'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedMachinesMachineIdEditRouteImport } from './routes/_authenticated/machines.$machineId.edit'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients.$clientId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepairsIndexRoute =
  AuthenticatedRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesMachineIdRoute =
  AuthenticatedMachinesMachineIdRouteImport.update({
    id: '/machines/$machineId',
    path: '/machines/$machineId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesMachineIdEditRoute =
  AuthenticatedMachinesMachineIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMachinesMachineIdRoute,
  } as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/repairs': typeof AuthenticatedRepairsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/machines/$machineId'
    | '/clients/'
    | '/repairs/'
    | '/clients/$clientId/edit'
    | '/machines/$machineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/machines/$machineId'
    | '/clients'
    | '/repairs'
    | '/clients/$clientId/edit'
    | '/machines/$machineId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/machines/$machineId'
    | '/_authenticated/clients/'
    | '/_authenticated/repairs/'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/machines/$machineId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/': {
      id: '/_authenticated/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthenticatedRepairsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/$machineId': {
      id: '/_authenticated/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof AuthenticatedMachinesMachineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/$machineId/edit': {
      id: '/_authenticated/machines/$machineId/edit'
      path: '/edit'
      fullPath: '/machines/$machineId/edit'
      preLoaderRoute: typeof AuthenticatedMachinesMachineIdEditRouteImport
      parentRoute: typeof AuthenticatedMachinesMachineIdRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedClientsClientIdRoute
    }
  }
}

interface AuthenticatedClientsClientIdRouteChildren {
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
}

const AuthenticatedClientsClientIdRouteChildren: AuthenticatedClientsClientIdRouteChildren =
  {
    AuthenticatedClientsClientIdEditRoute:
      AuthenticatedClientsClientIdEditRoute,
  }

const AuthenticatedClientsClientIdRouteWithChildren =
  AuthenticatedClientsClientIdRoute._addFileChildren(
    AuthenticatedClientsClientIdRouteChildren,
  )

interface AuthenticatedMachinesMachineIdRouteChildren {
  AuthenticatedMachinesMachineIdEditRoute: typeof AuthenticatedMachinesMachineIdEditRoute
}

const AuthenticatedMachinesMachineIdRouteChildren: AuthenticatedMachinesMachineIdRouteChildren =
  {
    AuthenticatedMachinesMachineIdEditRoute:
      AuthenticatedMachinesMachineIdEditRoute,
  }

const AuthenticatedMachinesMachineIdRouteWithChildren =
  AuthenticatedMachinesMachineIdRoute._addFileChildren(
    AuthenticatedMachinesMachineIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRouteWithChildren
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedMachinesMachineIdRoute: typeof AuthenticatedMachinesMachineIdRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedRepairsIndexRoute: typeof AuthenticatedRepairsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientsClientIdRoute:
    AuthenticatedClientsClientIdRouteWithChildren,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedMachinesMachineIdRoute:
    AuthenticatedMachinesMachineIdRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedRepairsIndexRoute: AuthenticatedRepairsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
